### ISSUE TITLE
tartube.db.lock is always present

### ISSUE THREAD

**Issue by BlueBlock** [angelics/unraid-docker-template#5]
Because unraid just shuts the container down, the tartube.db.lock file remains. I got tired of seeing that database lock file dialog.

Maybe there is a better way, but I have the following in "Post Arguments:" to remove the lock file as well as install yt-dlp and upgrade pip.

&& docker exec -u root Tartube bash -c "python3 -m pip install --upgrade pip && python3 -m pip install --no-deps -U yt-dlp && head -n -1 /startapp.sh > /tempfile && echo 'rm -f /storage/tartube.db.lock' >> /tempfile && echo 'exec tartube' >> /tempfile && chmod +x /tempfile && mv /tempfile /startapp.sh "

**Comment by angelics** [comment]
removing db.lock in new version
